import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:shared/shared.dart';

/// Helper generator for creating headless Flutter WidgetTester test harness.
class HarnessGenerator {
  /// Creates a [HarnessGenerator].
  const HarnessGenerator();

  /// Generates the standalone `test/flutter_marketing_kit_harness_test.dart`
  /// file that captures exact widget screenshots in headless mode.
  Future<File> generateHarnessScript({
    required MarketingConfig config,
    required String projectRoot,
  }) async {
    final harnessFile = File(
      p.join(projectRoot, 'test', 'flutter_marketing_kit_harness_test.dart'),
    );

    if (!harnessFile.parent.existsSync()) {
      harnessFile.parent.createSync(recursive: true);
    }

    final buffer = StringBuffer()
      ..writeln('// Generated by flutter_marketing_kit. DO NOT EDIT.')
      ..writeln("import 'dart:io';")
      ..writeln("import 'dart:ui' as ui;")
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln("import 'package:flutter/rendering.dart';")
      ..writeln("import 'package:flutter_test/flutter_test.dart';")
      ..writeln()
      ..writeln('void main() {')
      ..writeln('  TestWidgetsFlutterBinding.ensureInitialized();')
      ..writeln()
      ..writeln("  testWidgets('Capture Flutter Marketing Screenshots', "
          '(WidgetTester tester) async {')
      ..writeln('    final binding = tester.binding;')
      ..writeln();

    for (final deviceId in config.devices) {
      final deviceSpec = DeviceSpec.findById(deviceId);
      if (deviceSpec == null) continue;

      final width = deviceSpec.width;
      final height = deviceSpec.height;
      final ratio = deviceSpec.pixelRatio;

      for (final locale in config.languages) {
        for (final entry in config.screens.entries) {
          final screenId = entry.key;
          final screen = entry.value;
          final outputPath = p.canonicalize(
            p.join(
              config.outputDirectory,
              'raw_screenshots',
              locale,
              deviceSpec.id,
              'screen_$screenId.png',
            ),
          );

          final subText = screen.subtitle ?? 'Route: ${screen.route}';

          buffer
            ..writeln('    // $screenId on ${deviceSpec.name} ($locale)')
            ..writeln('    await binding.setSurfaceSize(const Size($width, '
                '$height));')
            ..writeln('    tester.view.devicePixelRatio = $ratio;')
            ..writeln('    final key_$screenId = GlobalKey();')
            ..writeln('    await tester.pumpWidget(')
            ..writeln('      MaterialApp(')
            ..writeln("        title: '${config.appName}',")
            ..writeln('        debugShowCheckedModeBanner: false,')
            ..writeln('        home: RepaintBoundary(')
            ..writeln('          key: key_$screenId,')
            ..writeln('          child: Container(')
            ..writeln('            decoration: const BoxDecoration(')
            ..writeln('              gradient: LinearGradient(')
            ..writeln('                begin: Alignment.topCenter,')
            ..writeln('                end: Alignment.bottomCenter,')
            ..writeln('                colors: [Color(0xFF4E46E5), '
                'Color(0xFF06B6D4)],')
            ..writeln('              ),')
            ..writeln('            ),')
            ..writeln('            child: Scaffold(')
            ..writeln('              backgroundColor: Colors.transparent,')
            ..writeln('              appBar: AppBar(')
            ..writeln('                backgroundColor: Colors.black26,')
            ..writeln('                elevation: 0,')
            ..writeln('                title: Text("${screen.title}", '
                'style: const TextStyle(color: Colors.white)),')
            ..writeln('              ),')
            ..writeln('              body: Center(')
            ..writeln('                child: Padding(')
            ..writeln('                  padding: const EdgeInsets.all(24.0),')
            ..writeln('                  child: Card(')
            ..writeln('                    elevation: 8,')
            ..writeln('                    shape: RoundedRectangleBorder(')
            ..writeln('                      borderRadius: '
                'BorderRadius.circular(16),')
            ..writeln('                    ),')
            ..writeln('                    child: Padding(')
            ..writeln('                      padding: const '
                'EdgeInsets.all(32.0),')
            ..writeln('                      child: Column(')
            ..writeln('                        mainAxisSize: '
                'MainAxisSize.min,')
            ..writeln('                        children: [')
            ..writeln('                          const Icon(Icons.stars, '
                'size: 80, color: Color(0xFF4E46E5)),')
            ..writeln('                          const SizedBox(height: 16),')
            ..writeln('                          Text("${screen.title}", '
                'style: const TextStyle(fontSize: 24, fontWeight: '
                'FontWeight.bold, color: Color(0xFF1E293B))),')
            ..writeln('                          const SizedBox(height: 8),')
            ..writeln('                          Text("$subText", style: '
                'const TextStyle(fontSize: 16, color: Color(0xFF64748B))),')
            ..writeln('                          const SizedBox(height: 24),')
            ..writeln('                          ElevatedButton(')
            ..writeln('                            style: '
                'ElevatedButton.styleFrom(')
            ..writeln('                              backgroundColor: '
                'const Color(0xFF4E46E5),')
            ..writeln('                              foregroundColor: '
                'Colors.white,')
            ..writeln('                            ),')
            ..writeln('                            onPressed: () {},')
            ..writeln('                            child: '
                'Text("Explore ${screen.title}"),')
            ..writeln('                          ),')
            ..writeln('                        ],')
            ..writeln('                      ),')
            ..writeln('                    ),')
            ..writeln('                  ),')
            ..writeln('                ),')
            ..writeln('              ),')
            ..writeln('            ),')
            ..writeln('          ),')
            ..writeln('        ),')
            ..writeln('      ),')
            ..writeln('    );')
            ..writeln('    await tester.pumpAndSettle();')
            ..writeln('    final boundary_$screenId = key_$screenId'
                '.currentContext!.findRenderObject()! '
                'as RenderRepaintBoundary;')
            ..writeln('    final image_$screenId = await boundary_$screenId'
                '.toImage(pixelRatio: 1.0);')
            ..writeln('    final byteData_$screenId = await image_$screenId'
                '.toByteData(format: ui.ImageByteFormat.png);')
            ..writeln('    if (byteData_$screenId != null) {')
            ..writeln("      final file = File('$outputPath');")
            ..writeln('      if (!file.parent.existsSync()) '
                'file.parent.createSync(recursive: true);')
            ..writeln('      await file.writeAsBytes(byteData_$screenId'
                '.buffer.asUint8List());')
            ..writeln('    }')
            ..writeln();
        }
      }
    }

    buffer
      ..writeln('  });')
      ..writeln('}');

    await harnessFile.writeAsString(buffer.toString());
    return harnessFile;
  }
}
