import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:shared/shared.dart';

/// Generates a Flutter widget test harness file inside the **calling project**
/// (the user's own app, not the package's example).
///
/// The generated test imports the user's real app widget, navigates to the
/// configured routes, and captures each screen via `matchesGoldenFile`.
/// Running it with `flutter test --update-goldens` produces real screenshots.
class HarnessGenerator {
  /// Creates a [HarnessGenerator].
  const HarnessGenerator();

  /// Reads `pubspec.yaml` at [projectRoot] and returns the `name:` field.
  String? _detectPackageName(String projectRoot) {
    final pubspec = File(p.join(projectRoot, 'pubspec.yaml'));
    if (!pubspec.existsSync()) return null;
    final content = pubspec.readAsStringSync();
    final match =
        RegExp(r'^name:\s*([a-zA-Z0-9_]+)', multiLine: true).firstMatch(content);
    return match?.group(1);
  }

  /// Reads `lib/main.dart` at [projectRoot] and returns the widget class
  /// passed to `runApp(...)`.
  String? _detectMainWidget(String projectRoot) {
    final mainDart = File(p.join(projectRoot, 'lib', 'main.dart'));
    if (!mainDart.existsSync()) return null;
    final content = mainDart.readAsStringSync();

    // Pattern 1: runApp(const MyApp()); or runApp(MyApp());
    final runAppMatch = RegExp(
      r'runApp\(\s*(?:const\s+|new\s+)?([A-Z][a-zA-Z0-9_]+)\s*\(',
    ).firstMatch(content);
    if (runAppMatch != null) {
      final name = runAppMatch.group(1)!;
      if (!const {'DevicePreview', 'ProviderScope', 'EasyLocalization'}
          .contains(name)) {
        return name;
      }
    }

    // Pattern 2: builder: (_) => MyApp() inside a wrapper
    final builderMatch = RegExp(
      r'builder:\s*\([^)]*\)\s*=>\s*(?:const\s+|new\s+)?([A-Z][a-zA-Z0-9_]+)\s*\(',
    ).firstMatch(content);
    if (builderMatch != null) return builderMatch.group(1);

    // Pattern 3: class MyApp extends StatelessWidget / StatefulWidget
    final classMatch = RegExp(
      r'class\s+([A-Z][a-zA-Z0-9_]+)\s+extends\s+(?:Stateless|Stateful)Widget',
    ).firstMatch(content);
    return classMatch?.group(1);
  }

  /// Generates `test/marketing_screenshots_test.dart` inside [projectRoot].
  ///
  /// Run the generated file with:
  /// ```dart
  /// flutter test test/marketing_screenshots_test.dart --update-goldens
  /// ```
  Future<File> generateHarnessScript({
    required MarketingConfig config,
    required String projectRoot,
  }) async {
    final harnessFile = File(
      p.join(projectRoot, 'test', 'marketing_screenshots_test.dart'),
    );

    if (!harnessFile.parent.existsSync()) {
      harnessFile.parent.createSync(recursive: true);
    }

    final packageName = _detectPackageName(projectRoot);
    final mainWidget = _detectMainWidget(projectRoot);
    final canImportApp = packageName != null && mainWidget != null;

    final buffer = StringBuffer()
      ..writeln('// Generated by flutter_marketing_kit — DO NOT EDIT.')
      ..writeln(
        '// Run: flutter test test/marketing_screenshots_test.dart'
        ' --update-goldens',
      )
      ..writeln()
      ..writeln("import 'package:flutter/material.dart';")
      ..writeln("import 'package:flutter_test/flutter_test.dart';");

    if (canImportApp) {
      buffer.writeln("import 'package:$packageName/main.dart';");
    }

    buffer
      ..writeln()
      ..writeln('void main() {')
      ..writeln('  testWidgets(')
      ..writeln("    'Marketing Screenshots',")
      ..writeln('    (WidgetTester tester) async {')
      ..writeln('      final binding = tester.binding;')
      ..writeln();

    for (final deviceId in config.devices) {
      final deviceSpec = DeviceSpec.findById(deviceId);
      if (deviceSpec == null) continue;

      final width = deviceSpec.width;
      final height = deviceSpec.height;
      final ratio = deviceSpec.pixelRatio;

      for (final locale in config.languages) {
        for (final entry in config.screens.entries) {
          final screenId = entry.key;
          final screen = entry.value;

          // Output path relative to projectRoot
          final outputPath = p.join(
            config.outputDirectory,
            'raw_screenshots',
            locale,
            deviceSpec.id,
            '${deviceSpec.id}_${screenId}_$locale.png',
          );

          // Golden path is relative to the test file (test/ dir → ../)
          final goldenPath = p.join('..', outputPath);

          final keyName = 'key_${deviceSpec.id}_${screenId}_$locale'
              .replaceAll('-', '_');

          buffer
            ..writeln(
              // ignore: missing_whitespace_between_adjacent_strings
              '      // ---'
              ' ${deviceSpec.name} | $screenId | $locale ---',
            )
            ..writeln(
              // ignore: missing_whitespace_between_adjacent_strings
              '      await binding.setSurfaceSize('
              'const Size($width, $height));',
            )
            ..writeln('      tester.view.devicePixelRatio = $ratio;')
            ..writeln('      final $keyName = GlobalKey();');

          if (canImportApp) {
            // Boot the user's REAL app and navigate to the configured route
            buffer
              ..writeln('      await tester.pumpWidget(')
              ..writeln('        RepaintBoundary(')
              ..writeln('          key: $keyName,')
              ..writeln('          child: $mainWidget(),')
              ..writeln('        ),')
              ..writeln('      );')
              ..writeln('      await tester.pumpAndSettle();');

            if (screen.route != '/') {
              buffer
                ..writeln('      try {')
                ..writeln(
                  // ignore: missing_whitespace_between_adjacent_strings
                  '        tester.state<NavigatorState>'
                  '(find.byType(Navigator))',
                )
                ..writeln("          .pushNamed('${screen.route}');")
                ..writeln('        await tester.pumpAndSettle();')
                ..writeln('      } catch (e) {')
                ..writeln(
                  "        debugPrint('Could not navigate to "
                  "${screen.route}: \$e');",
                )
                ..writeln('      }');
            }
          } else {
            // Fallback: can't import app — render a labelled placeholder
            final subtitle = screen.subtitle ?? screen.route;
            buffer
              ..writeln('      await tester.pumpWidget(')
              ..writeln('        MaterialApp(')
              ..writeln('          debugShowCheckedModeBanner: false,')
              ..writeln('          home: RepaintBoundary(')
              ..writeln('            key: $keyName,')
              ..writeln('            child: Scaffold(')
              ..writeln(
                '              backgroundColor: const Color(0xFF1A1A2E),',
              )
              ..writeln('              body: Center(')
              ..writeln('                child: Column(')
              ..writeln('                  mainAxisSize: MainAxisSize.min,')
              ..writeln('                  children: [')
              ..writeln("                    Text('${screen.title}',")
              ..writeln(
                '                      style: const TextStyle(',
              )
              ..writeln(
                '                        color: Colors.white,',
              )
              ..writeln(
                '                        fontSize: 28,',
              )
              ..writeln(
                '                        fontWeight: FontWeight.bold,',
              )
              ..writeln('                      ),')
              ..writeln('                    ),')
              ..writeln('                    const SizedBox(height: 8),')
              ..writeln("                    Text('$subtitle',")
              ..writeln('                      style: const TextStyle(')
              ..writeln(
                '                        color: Colors.white70,',
              )
              ..writeln('                        fontSize: 16,')
              ..writeln('                      ),')
              ..writeln('                    ),')
              ..writeln('                  ],')
              ..writeln('                ),')
              ..writeln('              ),')
              ..writeln('            ),')
              ..writeln('          ),')
              ..writeln('        ),')
              ..writeln('      );')
              ..writeln('      await tester.pumpAndSettle();');
          }

          // Capture via golden matcher
          buffer
            ..writeln('      await expectLater(')
            ..writeln('        find.byKey($keyName),')
            ..writeln("        matchesGoldenFile('$goldenPath'),")
            ..writeln('      );')
            ..writeln();
        }
      }
    }

    buffer
      ..writeln('    },')
      ..writeln('  );')
      ..writeln('}');

    await harnessFile.writeAsString(buffer.toString());
    return harnessFile;
  }
}
