name: example
description: Production example application showcasing flutter_marketing_kit automation.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_marketing_kit:
    path: ../packages/flutter_marketing_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  image: ^4.8.0

