import 'package:ai_engine/src/providers/ai_provider.dart';
import 'package:ai_engine/src/providers/ai_providers_impl.dart';

/// Marketing copy generated by AI or offline fallback template.
class GeneratedMarketingCopy {
  /// Creates a [GeneratedMarketingCopy] instance.
  const GeneratedMarketingCopy({
    required this.shortDescription,
    required this.fullDescription,
    required this.keywords,
    required this.releaseNotes,
    required this.faqList,
    required this.privacyPolicy,
    required this.termsOfService,
  });

  /// Short app store description (max 80 chars).
  final String shortDescription;

  /// Full app store description.
  final String fullDescription;

  /// ASO keywords list.
  final List<String> keywords;

  /// Version release notes.
  final String releaseNotes;

  /// List of FAQ question/answer pairs.
  final List<String> faqList;

  /// Privacy policy text content.
  final String privacyPolicy;

  /// Terms of service text content.
  final String termsOfService;
}

/// Primary AI Engine manager for marketing copy and ASO optimization.
class AiEngine {
  /// Creates an [AiEngine] instance.
  const AiEngine({
    Map<String, AiProvider>? providers,
  }) : _providers = providers ??
            const {
              'gemini': GeminiAiProvider(),
              'openai': OpenAiProvider(),
              'anthropic': AnthropicAiProvider(),
              'openrouter': OpenRouterAiProvider(),
              'ollama': OllamaAiProvider(),
              'lmstudio': LmStudioAiProvider(),
            };

  final Map<String, AiProvider> _providers;

  /// Available registered provider names.
  List<String> get availableProviders => _providers.keys.toList();

  /// Generate marketing copy for application using AI key or offline fallback.
  Future<GeneratedMarketingCopy> generateCopy({
    required String appName,
    String? apiKey,
    String providerKey = 'gemini',
  }) async {
    if (apiKey != null &&
        apiKey.isNotEmpty &&
        _providers.containsKey(providerKey)) {
      final provider = _providers[providerKey]!;
      final prompt = 'Generate ASO description for $appName';
      final generatedText = await provider.generateText(
        prompt: prompt,
        apiKey: apiKey,
      );

      return GeneratedMarketingCopy(
        shortDescription: '$appName - Smart & intuitive application.',
        fullDescription: '$generatedText\n\nDownload $appName today!',
        keywords: [appName.toLowerCase(), 'flutter', 'app', 'utility'],
        releaseNotes: '• Minor performance improvements and bug fixes.',
        faqList: ['Q: Is $appName free to use?\nA: Yes, absolutely!'],
        privacyPolicy: 'Privacy Policy for $appName: We respect user privacy.',
        termsOfService: 'Terms of Service for $appName: Use responsibly.',
      );
    }

    const faqText = 'Q: Is app offline friendly?\nA: Yes, 100% offline.';
    const privacyText =
        'Privacy Policy: Operates 100% offline and respects privacy.';

    // 100% Offline fallback output when no AI API key is provided
    return GeneratedMarketingCopy(
      shortDescription: '$appName - Designed for maximum productivity.',
      fullDescription:
          '$appName is a Flutter app built to streamline your workflow.',
      keywords: [appName.toLowerCase(), 'flutter', 'productivity'],
      releaseNotes: '• Initial production release with automated assets.',
      faqList: const [faqText],
      privacyPolicy: privacyText,
      termsOfService:
          'Terms of Service: Standard software license terms apply.',
    );
  }
}
