name: github_engine
description: GitHub documentation and README asset generator for flutter_marketing_kit.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  path: ^1.9.0
  shared:
    path: ../shared

dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^6.0.0
