// Generated by flutter_marketing_kit — DO NOT EDIT.
// Run: flutter test test/marketing_screenshots_test.dart --update-goldens

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:example/main.dart';

void main() {
  testWidgets(
    'Marketing Screenshots',
    (WidgetTester tester) async {
      final binding = tester.binding;

      // --- Google Pixel 9 | home | en ---
      await binding.setSurfaceSize(const Size(1080.0, 2424.0));
      tester.view.devicePixelRatio = 3.0;
      final key_pixel9_home_en = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key_pixel9_home_en,
          child: MarketingKitExampleApp(),
        ),
      );
      await tester.pumpAndSettle();
      await expectLater(
        find.byKey(key_pixel9_home_en),
        matchesGoldenFile('../marketing/raw_screenshots/en/pixel9/pixel9_home_en.png'),
      );

      // --- Google Pixel 9 | premium | en ---
      await binding.setSurfaceSize(const Size(1080.0, 2424.0));
      tester.view.devicePixelRatio = 3.0;
      final key_pixel9_premium_en = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key_pixel9_premium_en,
          child: MarketingKitExampleApp(),
        ),
      );
      await tester.pumpAndSettle();
      try {
        tester.state<NavigatorState>(find.byType(Navigator))
          .pushNamed('/premium');
        await tester.pumpAndSettle();
      } catch (e) {
        debugPrint('Could not navigate to /premium: $e');
      }
      await expectLater(
        find.byKey(key_pixel9_premium_en),
        matchesGoldenFile('../marketing/raw_screenshots/en/pixel9/pixel9_premium_en.png'),
      );

      // --- Google Pixel 9 | settings | en ---
      await binding.setSurfaceSize(const Size(1080.0, 2424.0));
      tester.view.devicePixelRatio = 3.0;
      final key_pixel9_settings_en = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key_pixel9_settings_en,
          child: MarketingKitExampleApp(),
        ),
      );
      await tester.pumpAndSettle();
      try {
        tester.state<NavigatorState>(find.byType(Navigator))
          .pushNamed('/settings');
        await tester.pumpAndSettle();
      } catch (e) {
        debugPrint('Could not navigate to /settings: $e');
      }
      await expectLater(
        find.byKey(key_pixel9_settings_en),
        matchesGoldenFile('../marketing/raw_screenshots/en/pixel9/pixel9_settings_en.png'),
      );

      // --- iPhone 16 | home | en ---
      await binding.setSurfaceSize(const Size(1179.0, 2556.0));
      tester.view.devicePixelRatio = 3.0;
      final key_iphone16_home_en = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key_iphone16_home_en,
          child: MarketingKitExampleApp(),
        ),
      );
      await tester.pumpAndSettle();
      await expectLater(
        find.byKey(key_iphone16_home_en),
        matchesGoldenFile('../marketing/raw_screenshots/en/iphone16/iphone16_home_en.png'),
      );

      // --- iPhone 16 | premium | en ---
      await binding.setSurfaceSize(const Size(1179.0, 2556.0));
      tester.view.devicePixelRatio = 3.0;
      final key_iphone16_premium_en = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key_iphone16_premium_en,
          child: MarketingKitExampleApp(),
        ),
      );
      await tester.pumpAndSettle();
      try {
        tester.state<NavigatorState>(find.byType(Navigator))
          .pushNamed('/premium');
        await tester.pumpAndSettle();
      } catch (e) {
        debugPrint('Could not navigate to /premium: $e');
      }
      await expectLater(
        find.byKey(key_iphone16_premium_en),
        matchesGoldenFile('../marketing/raw_screenshots/en/iphone16/iphone16_premium_en.png'),
      );

      // --- iPhone 16 | settings | en ---
      await binding.setSurfaceSize(const Size(1179.0, 2556.0));
      tester.view.devicePixelRatio = 3.0;
      final key_iphone16_settings_en = GlobalKey();
      await tester.pumpWidget(
        RepaintBoundary(
          key: key_iphone16_settings_en,
          child: MarketingKitExampleApp(),
        ),
      );
      await tester.pumpAndSettle();
      try {
        tester.state<NavigatorState>(find.byType(Navigator))
          .pushNamed('/settings');
        await tester.pumpAndSettle();
      } catch (e) {
        debugPrint('Could not navigate to /settings: $e');
      }
      await expectLater(
        find.byKey(key_iphone16_settings_en),
        matchesGoldenFile('../marketing/raw_screenshots/en/iphone16/iphone16_settings_en.png'),
      );

    },
  );
}
