name: navigation_engine
description: Navigation automation, route observation, state injection, and mock data binding engine for flutter_marketing_kit.
version: 1.0.0
homepage: https://github.com/mohamedmekawy/flutter_marketing_kit
repository: https://github.com/mohamedmekawy/flutter_marketing_kit

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  meta: ^1.11.0
  shared:
    path: ../shared

dev_dependencies:
  test: ^1.25.0
  very_good_analysis: ^6.0.0
