import 'package:config_engine/src/config_validator.dart';
import 'package:shared/shared.dart';
import 'package:yaml/yaml.dart';

/// YAML Configuration parser and template generator.
class YamlConfigParser {
  /// Creates a [YamlConfigParser] with an optional validator.
  const YamlConfigParser({
    ConfigValidator validator = const ConfigValidator(),
  }) : _validator = validator;

  final ConfigValidator _validator;

  /// Parse YAML string into a strongly-typed, validated [MarketingConfig].
  MarketingConfig parse(String yamlContent) {
    dynamic yaml;
    try {
      yaml = loadYaml(yamlContent);
    } catch (e) {
      throw ConfigurationException(
        'Failed to parse YAML file structure.',
        details: e.toString(),
        suggestion: 'Ensure valid YAML formatting without syntax errors.',
      );
    }

    if (yaml is! YamlMap) {
      throw const ConfigurationException(
        'YAML root must be a map of key-value pairs.',
        suggestion: 'Ensure playstore_assets.yaml begins with app_name:',
      );
    }

    final appName = (yaml['app_name'] as String?) ?? '';
    final packageName = (yaml['package_name'] as String?) ?? '';
    final outputDirectory =
        (yaml['output_directory'] as String?) ?? 'marketing';
    final theme = (yaml['theme'] as String?) ?? 'modern';
    final template = (yaml['template'] as String?) ?? 'gaming';
    final primaryColor = (yaml['primary_color'] as String?) ?? '#5E5CE6';
    final accentColor = (yaml['accent_color'] as String?) ?? '#00C2FF';

    final rawDevices = yaml['devices'];
    final devices = <String>[];
    if (rawDevices is YamlList) {
      devices.addAll(rawDevices.map((e) => e.toString()));
    }

    final rawLanguages = yaml['languages'];
    final languages = <String>[];
    if (rawLanguages is YamlList) {
      languages.addAll(rawLanguages.map((e) => e.toString()));
    } else {
      languages.add('en');
    }

    final rawScreens = yaml['screens'];
    final screens = <String, ScreenSpec>{};
    if (rawScreens is YamlMap) {
      rawScreens.forEach((key, value) {
        final screenId = key.toString();
        if (value is YamlMap) {
          final route = (value['route'] as String?) ?? '/';
          final title = (value['title'] as String?) ?? screenId;
          final subtitle = value['subtitle'] as String?;
          screens[screenId] = ScreenSpec(
            id: screenId,
            route: route,
            title: title,
            subtitle: subtitle,
          );
        }
      });
    }

    final aiMap = yaml['ai'];
    String? aiApiKey;
    var aiProvider = 'gemini';
    if (aiMap is YamlMap) {
      aiApiKey = aiMap['api_key'] as String?;
      aiProvider = (aiMap['provider'] as String?) ?? 'gemini';
    }

    final config = MarketingConfig(
      appName: appName,
      packageName: packageName,
      outputDirectory: outputDirectory,
      theme: theme,
      template: template,
      primaryColor: primaryColor,
      accentColor: accentColor,
      devices: devices,
      languages: languages,
      screens: screens,
      aiApiKey: aiApiKey,
      aiProvider: aiProvider,
    );

    _validator.validate(config);
    return config;
  }

  /// Generates the default `playstore_assets.yaml` configuration template.
  static String generateDefaultConfigYaml() {
    return '''
# ==============================================================================
# FLUTTER MARKETING KIT CONFIGURATION
# Generated by `dart run flutter_marketing_kit init`
# ==============================================================================

# General Application Information
app_name: Expense AI
package_name: com.example.expense
output_directory: marketing

# Visual Design Theme and Preset
# Supported Themes: modern, minimal, material, gaming, kids, finance, health
theme: modern
template: gaming

# Branding Colors (HEX Format)
primary_color: "#5E5CE6"
accent_color: "#00C2FF"

# Target Devices for Framing and Screenshots
# Phone: pixel9, iphone16, iphone16Pro, iphoneSE, galaxyS25, pixelFold
# Tablet: ipad, ipadAir, ipadPro, galaxyTab
devices:
  - pixel9
  - iphone16
  - ipad

# Localization Locales
languages:
  - en
  - ar

# Target Application Routes & Screenshot Captions
screens:
  home:
    route: /
    title: Smart Dashboard
    subtitle: Track your expenses in real-time
  premium:
    route: /premium
    title: Premium Features
    subtitle: Unlock unlimited budgets & analytics
  settings:
    route: /settings
    title: Seamless Controls
    subtitle: Customize themes, currencies & privacy

# Optional AI Integration Settings
# AI features are 100% optional.
# Supported Providers: gemini, openai, anthropic, openrouter, ollama, lmstudio
ai:
  provider: gemini
  # api_key: "YOUR_API_KEY_HERE"
''';
  }
}
